/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TmsRouteImport } from './routes/tms'
import { Route as TgdRouteImport } from './routes/tgd'
import { Route as TmsPrivacyRouteImport } from './routes/tms_.privacy'
import { Route as TmsTermsRouteImport } from './routes/tms_.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const TmsRoute = TmsRouteImport.update({
  id: '/tms',
  path: '/tms',
  getParentRoute: () => rootRouteImport,
} as any)

const TgdRoute = TgdRouteImport.update({
  id: '/tgd',
  path: '/tgd',
  getParentRoute: () => rootRouteImport,
} as any)

const TmsPrivacyRoute = TmsPrivacyRouteImport.update({
  id: '/tms_/privacy',
  path: '/tms/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

const TmsTermsRoute = TmsTermsRouteImport.update({
  id: '/tms_/terms',
  path: '/tms/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tms': typeof TmsRoute
  '/tgd': typeof TgdRoute
  '/tms/privacy': typeof TmsPrivacyRoute
  '/tms/terms': typeof TmsTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tms': typeof TmsRoute
  '/tgd': typeof TgdRoute
  '/tms/privacy': typeof TmsPrivacyRoute
  '/tms/terms': typeof TmsTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tms': typeof TmsRoute
  '/tgd': typeof TgdRoute
  '/tms_/privacy': typeof TmsPrivacyRoute
  '/tms_/terms': typeof TmsTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tms' | '/tgd' | '/tms/privacy' | '/tms/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tms' | '/tgd' | '/tms/privacy' | '/tms/terms'
  id: '__root__' | '/' | '/tms' | '/tgd' | '/tms_/privacy' | '/tms_/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TmsRoute: typeof TmsRoute
  TgdRoute: typeof TgdRoute
  TmsPrivacyRoute: typeof TmsPrivacyRoute
  TmsTermsRoute: typeof TmsTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tms': {
      id: '/tms'
      path: '/tms'
      fullPath: '/tms'
      preLoaderRoute: typeof TmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tgd': {
      id: '/tgd'
      path: '/tgd'
      fullPath: '/tgd'
      preLoaderRoute: typeof TgdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tms_/privacy': {
      id: '/tms_/privacy'
      path: '/tms/privacy'
      fullPath: '/tms/privacy'
      preLoaderRoute: typeof TmsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tms_/terms': {
      id: '/tms_/terms'
      path: '/tms/terms'
      fullPath: '/tms/terms'
      preLoaderRoute: typeof TmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TmsRoute: TmsRoute,
  TgdRoute: TgdRoute,
  TmsPrivacyRoute: TmsPrivacyRoute,
  TmsTermsRoute: TmsTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
